-- Run this entire script once in the Supabase SQL editor (Dashboard -> SQL -> New query).
-- It creates the tables used by this app and grants the publishable (anon) key
-- full CRUD access. Row Level Security is disabled because the app authenticates
-- users on its own Flask session layer and always filters queries by user_id,
-- so per-user isolation is enforced in the application, not the database.
-- Do not expose SUPABASE_PUBLISHABLE_KEY in any public frontend code.

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null unique,
  password text,
  google_sub text unique,
  budget bigint not null default 0,
  threshold bigint not null default 80,
  auto_sync boolean not null default false
);

create table if not exists public.pockets (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  name text not null,
  target bigint not null,
  balance bigint not null default 0 check (balance >= 0)
);

create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  description text not null,
  amount bigint not null check (amount > 0),
  kind text not null,
  category text not null,
  date text not null,
  source text not null default 'manual'
);

create table if not exists public.gmail (
  user_id bigint primary key references public.users(id) on delete cascade,
  token text not null,
  email text,
  last_sync text
);

create table if not exists public.imports (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  message_id text not null,
  description text,
  amount bigint,
  kind text,
  category text,
  date text,
  status text not null default 'pending',
  unique (user_id, message_id)
);

create table if not exists public.attempts (
  key text primary key,
  count bigint not null,
  started double precision not null
);

create index if not exists transactions_user_idx on public.transactions (user_id);
create index if not exists pockets_user_idx on public.pockets (user_id);
create index if not exists imports_user_idx on public.imports (user_id);

alter table public.users disable row level security;
alter table public.pockets disable row level security;
alter table public.transactions disable row level security;
alter table public.gmail disable row level security;
alter table public.imports disable row level security;
alter table public.attempts disable row level security;

grant usage on schema public to anon, authenticated;
grant all on all tables in schema public to anon, authenticated;
grant all on all sequences in schema public to anon, authenticated;
grant all on all routines in schema public to anon, authenticated;